/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Utilizador
 * Created: 11/dez/2019
 */
DROP TABLE CLIENTS              CASCADE CONSTRAINTS PURGE;
DROP TABLE CREDIT_CARDS         CASCADE CONSTRAINTS PURGE;
DROP TABLE PLACES               CASCADE CONSTRAINTS PURGE;
DROP TABLE PARKS                CASCADE CONSTRAINTS PURGE;
DROP TABLE POI                  CASCADE CONSTRAINTS PURGE;
DROP TABLE PATHS                CASCADE CONSTRAINTS PURGE;
DROP TABLE VEHICLES             CASCADE CONSTRAINTS PURGE;
DROP TABLE BICYCLES             CASCADE CONSTRAINTS PURGE;
DROP TABLE SCOOTERS             CASCADE CONSTRAINTS PURGE;
DROP TABLE VEHICLE_REQUESTS     CASCADE CONSTRAINTS PURGE;
DROP TABLE VehicleRequests_Path CASCADE CONSTRAINTS PURGE;
DROP TABLE INVOICE              CASCADE CONSTRAINTS PURGE;
DROP TABLE INVOICE_LINE         CASCADE CONSTRAINTS PURGE;
DROP TABLE VEHICLES_CHARGING_HISTORY CASCADE CONSTRAINTS PURGE;